# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  workflow_dispatch:
     inputs:
       buildConfiguration:
         description: 'Build Configuration'
         default: 'Release'
         type: choice
         options:
         - 'Debug'
         - 'Release'
         required: true

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Determined by workflow_dispatch input "buildConfiguration"
  BUILD_CONFIGURATION: ${{ inputs.buildConfiguration }}

permissions:
  contents: read

jobs:
  log-the-inputs:
    runs-on: windows-latest
    steps:
      - run: |
          echo "Build Configuration: $BUILDCONFIG"
        env:
          BUILDCONFIG: ${{ inputs.buildConfiguration }}

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Get current timestamp
      run: echo "TIMESTAMP=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ github.sha }}-{{ $TIMESTAMP }} # Artifact name. Must be unique, so mix in commit hash and timestamp.
        path: ${{env.SOLUTION_FILE_PATH}}/MockExternal/bin/${{ inputs.buildConfiguration }}/net7.0-windows
        if-no-files-found: error

